import { useState } from 'react';
import { Mail, Phone, MapPin, Heart, Send, CheckCircle2, Users, HandHeart, BookOpen, ShieldCheck, Sparkles } from 'lucide-react';
import { IMAGES } from '@/lib/images';
import { getSupabase } from '@/lib/supabase';

const counties = ['Kisumu', 'Siaya', 'Homa Bay', 'Migori', 'Kakamega', 'Bungoma', 'Busia', 'Vihiga', 'Nairobi', 'Other'];

export default function Contact() {
  return <div><section className="relative bg-forest-gradient pt-40 pb-24 overflow-hidden"><div className="absolute inset-0 opacity-15"><img src={IMAGES.volunteerHandover} alt="" className="w-full h-full object-cover" /></div><div className="absolute top-0 left-0 w-[500px] h-[500px] bg-gold-300/10 rounded-full blur-3xl -translate-y-1/2 -translate-x-1/3" /><div className="container-page relative z-10"><div className="max-w-3xl"><div className="section-eyebrow text-gold-300 mb-5"><Heart className="w-4 h-4" /> Join the Movement</div><h1 className="text-4xl sm:text-5xl lg:text-6xl font-serif font-semibold text-white mb-6">Be Part of the Light</h1><p className="text-lg sm:text-xl text-sand-100/80 leading-relaxed max-w-2xl">Justice grows when people come together. Become a member, support our work, or reach out to start a conversation.</p></div></div></section><section className="py-24 bg-sand-50"><div className="container-page"><div className="grid grid-cols-1 lg:grid-cols-5 gap-14 items-start"><div className="lg:col-span-2 lg:sticky lg:top-28"><div className="section-eyebrow mb-4"><Users className="w-4 h-4" /> Get Involved</div><h2 className="text-3xl sm:text-4xl font-serif font-semibold text-forest-950 mb-5">Your voice belongs in this movement.</h2><p className="text-forest-800/70 leading-relaxed mb-8">Membership is a commitment to stand for equal access to justice and to help build communities where legal knowledge is not a privilege, but a shared right.</p><div className="space-y-5 mb-10">{[{ icon: HandHeart, title: 'Stand with communities', text: 'Support grassroots legal literacy and mediation.' }, { icon: BookOpen, title: 'Grow your knowledge', text: 'Access resources and learn from lived experience.' }, { icon: Users, title: 'Build the network', text: 'Connect with advocates, paralegals, and changemakers.' }].map((item) => <div key={item.title} className="flex items-start gap-4"><div className="w-10 h-10 rounded-xl bg-gold-100 flex items-center justify-center shrink-0"><item.icon className="w-5 h-5 text-gold-600" /></div><div><h3 className="font-serif text-lg font-semibold text-forest-900">{item.title}</h3><p className="text-sm text-forest-800/60">{item.text}</p></div></div>)}</div><div className="rounded-2xl bg-forest-900 p-6 text-sand-100/80"><h3 className="font-serif text-lg font-semibold text-white mb-4">Talk to us</h3><div className="space-y-3 text-sm"><div className="flex items-center gap-3"><Mail className="w-4 h-4 text-gold-300" />info@mwangazawasheria.org</div><div className="flex items-center gap-3"><Phone className="w-4 h-4 text-gold-300" />+254 700 000 000</div><div className="flex items-start gap-3"><MapPin className="w-4 h-4 text-gold-300 mt-0.5" />Western & Nyanza Regional Offices, Kenya</div></div></div></div><div className="lg:col-span-3"><MembershipForm /></div></div></div></section></div>;
}

function MembershipForm() {
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { const { error: insertError } = await getSupabase().from('membership_applications').insert({ full_name: form.get('full_name'), email: form.get('email'), phone: form.get('phone'), id_number: form.get('id_number'), county: form.get('county'), occupation: form.get('occupation'), reason: form.get('reason'), commitment_oath: form.get('commitment_oath') === 'on' }); if (insertError) throw insertError; setSubmitted(true); } catch { setError('We could not submit your application right now. Please try again or contact us directly.'); } finally { setLoading(false); } }
  if (submitted) return <div className="bg-white rounded-3xl shadow-card p-8 sm:p-12 text-center"><div className="w-16 h-16 rounded-full bg-forest-100 flex items-center justify-center mx-auto mb-6"><CheckCircle2 className="w-8 h-8 text-forest-600" /></div><h2 className="text-3xl font-serif font-semibold text-forest-950 mb-4">Application received</h2><p className="text-forest-800/70 leading-relaxed max-w-md mx-auto mb-8">Thank you for choosing to stand with Mwangaza wa Sheria. Our team will review your application and be in touch soon.</p><button onClick={() => setSubmitted(false)} className="btn-outline">Submit another application</button></div>;
  return <form onSubmit={handleSubmit} className="bg-white rounded-3xl shadow-card p-7 sm:p-10"><div className="section-eyebrow mb-3"><Sparkles className="w-4 h-4" /> Membership Application</div><h2 className="text-3xl font-serif font-semibold text-forest-950 mb-2">Become a member</h2><p className="text-sm text-forest-800/60 mb-8">Please share a few details so we can welcome you properly.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-5"><Field name="full_name" label="Full name" required /><Field name="email" label="Email address" type="email" required /><Field name="phone" label="Phone number" required /><Field name="id_number" label="National ID number" /><Field name="county" label="County of residence" type="select" required /><Field name="occupation" label="Occupation" /></div><div className="mt-5"><label htmlFor="reason" className="block text-xs font-semibold uppercase tracking-wider text-forest-800/70 mb-2">Why would you like to join?</label><textarea id="reason" name="reason" rows={4} className="w-full px-4 py-3 rounded-xl border border-sand-300 bg-white text-sm text-forest-950 outline-none focus:border-gold-400 focus:ring-2 focus:ring-gold-200 resize-none" placeholder="Tell us what draws you to this movement..." /></div><label className="flex items-start gap-3 mt-6 cursor-pointer"><input name="commitment_oath" type="checkbox" required className="mt-1 w-4 h-4 accent-forest-600" /><span className="text-sm text-forest-800/70 leading-relaxed">I commit to uphold the values of Mwangaza wa Sheria Organization and to support its mission of equal access to justice.</span></label>{error && <p className="text-sm text-red-700 bg-red-50 rounded-xl px-4 py-3 mt-5">{error}</p>}<button type="submit" disabled={loading} className="btn-primary w-full mt-7 disabled:opacity-60">{loading ? 'Submitting application...' : 'Submit membership application'} <Send className="w-4 h-4" /></button><div className="flex items-start gap-2 mt-5 text-[11px] text-forest-800/45"><ShieldCheck className="w-4 h-4 shrink-0" /><span>Your information is kept confidential and will only be used to process your membership application.</span></div></form>;
}

function Field({ name, label, type = 'text', required = false }: { name: string; label: string; type?: string; required?: boolean }) {
  return <div><label htmlFor={name} className="block text-xs font-semibold uppercase tracking-wider text-forest-800/70 mb-2">{label}{required && <span className="text-gold-600"> *</span>}</label>{type === 'select' ? <select id={name} name={name} required={required} defaultValue="" className="w-full px-4 py-3 rounded-xl border border-sand-300 bg-white text-sm text-forest-950 outline-none focus:border-gold-400 focus:ring-2 focus:ring-gold-200"><option value="" disabled>Select county</option>{counties.map((county) => <option key={county} value={county}>{county}</option>)}</select> : <input id={name} name={name} type={type} required={required} className="w-full px-4 py-3 rounded-xl border border-sand-300 bg-white text-sm text-forest-950 outline-none focus:border-gold-400 focus:ring-2 focus:ring-gold-200" />}</div>;
}
